.PHONY: install test run serve deploy demo clean

# Install deps into a local .venv (Windows: copy commands from run.sh/run-tests.sh)
install:
	uv venv .venv && . .venv/Scripts/activate && uv pip install -e ".[dev,adk]"

# Run the pytest suite in mock mode (no credentials required)
test:
	bash run-tests.sh

# Run the live screening pipeline once (mock mode) and print the result + trace
run:
	env -u PYTHONPATH KNOTULUS_ROOT="$(PWD)" ENABLE_GEMINI=false .venv/Scripts/python.exe src/orchestrator.py

# Start the FastAPI gateway (Agent Gateway) on :8080
serve:
	env -u PYTHONPATH KNOTULUS_ROOT="$(PWD)" .venv/Scripts/python.exe -m src.gateway

# Deploy to Cloud Run (scales-to-zero). Edit PROJECT_ID/REGION in deploy.sh first.
deploy:
	bash deploy.sh

# Clean runtime artifacts (memory + traces) — regenerated by the pipeline
clean:
	rm -rf memory/*.json traces/*.md .pytest_cache
